# Generated by Django 4.2.6 on 2024-05-09 14:33

from django.db import migrations, models
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("slth", "0006_user"),
        ("comum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anexosolicitacao",
            options={
                "verbose_name": "Anexo de Solicitação",
                "verbose_name_plural": "Anexos de Solicitação",
            },
        ),
        migrations.AlterModelOptions(
            name="areatematica",
            options={
                "ordering": ("nome",),
                "verbose_name": "Área Temática",
                "verbose_name_plural": "Áreas Temáticas",
            },
        ),
        migrations.AlterModelOptions(
            name="avaliacaosolicitacao",
            options={
                "verbose_name": "Avaliação de Solicitação",
                "verbose_name_plural": "Avaliações de Solicitação",
            },
        ),
        migrations.AlterModelOptions(
            name="categoriaprofissional",
            options={
                "verbose_name": "Categoria Profissional",
                "verbose_name_plural": "Categorias Profissionais",
            },
        ),
        migrations.AlterModelOptions(
            name="estabelecimentosaude",
            options={
                "verbose_name": "Estabelecimento de Saúde",
                "verbose_name_plural": "Estabelecimentos de Saúde",
            },
        ),
        migrations.AlterModelOptions(
            name="fluxosolicitacao",
            options={
                "verbose_name": "Histórico de Solicitação",
                "verbose_name_plural": "Histórico de Solicitação",
            },
        ),
        migrations.AlterModelOptions(
            name="historicoalteracaoprofissional",
            options={
                "verbose_name": "Histórico de Alteração Profissional",
                "verbose_name_plural": "Histórico de Alteração de Profissional",
            },
        ),
        migrations.AlterModelOptions(
            name="motivoencerramentoconferencia",
            options={
                "verbose_name": "Motivo de Encerramento de Conferência",
                "verbose_name_plural": "Motivos de Encerramento de Conferência",
            },
        ),
        migrations.AlterModelOptions(
            name="municipio",
            options={"verbose_name": "Município", "verbose_name_plural": "Municípios"},
        ),
        migrations.AlterModelOptions(
            name="nivelformacao",
            options={
                "verbose_name": "Nível de Formação",
                "verbose_name_plural": "Níveis de Formação",
            },
        ),
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfis"},
        ),
        migrations.AlterModelOptions(
            name="profissionalsaude",
            options={
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitacao",
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
            },
        ),
        migrations.AlterModelOptions(
            name="statussolicitacao",
            options={
                "verbose_name": "Status de Solicitação",
                "verbose_name_plural": "Status de Solicitação",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoenfoqueresposta",
            options={
                "ordering": ("nome",),
                "verbose_name": "Enfoque de Solicitação de Resposta",
                "verbose_name_plural": "Enfoques de Solicitação de Resposta",
            },
        ),
        migrations.AlterModelOptions(
            name="tiposolicitacao",
            options={
                "verbose_name": "Tipo de Serviço",
                "verbose_name_plural": "Tipos de Serviços",
            },
        ),
        migrations.AlterModelOptions(
            name="unidadefederativa",
            options={
                "ordering": ["nome"],
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "verbose_name": "Pessoa Física",
                "verbose_name_plural": "Pessoas Físicas",
            },
        ),
        migrations.AddField(
            model_name="estabelecimentosaude",
            name="foto",
            field=slth.db.models.ImageField(
                blank=True,
                null=True,
                upload_to="estabelecimentos_saude",
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="estabelecimentosaude",
            name="gestores",
            field=slth.db.models.ManyToManyField(
                blank=True, to="comum.usuario", verbose_name="Gestores"
            ),
        ),
        migrations.AddField(
            model_name="estabelecimentosaude",
            name="latitude",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AddField(
            model_name="estabelecimentosaude",
            name="longitude",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Longitude"
            ),
        ),
        migrations.AddField(
            model_name="estabelecimentosaude",
            name="operadores",
            field=slth.db.models.ManyToManyField(
                blank=True,
                related_name="estabelecimentos_operados",
                to="comum.usuario",
                verbose_name="Operadores",
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="gestores",
            field=slth.db.models.ManyToManyField(
                blank=True,
                related_name="municipios_gerenciados",
                to="comum.usuario",
                verbose_name="Gestores",
            ),
        ),
        migrations.AddField(
            model_name="profissionalsaude",
            name="ativo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profissionalsaude",
            name="especialidade",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comum.especialidade",
            ),
        ),
        migrations.AddField(
            model_name="profissionalsaude",
            name="estabelecimento",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comum.estabelecimentosaude",
            ),
        ),
        migrations.AddField(
            model_name="profissionalsaude",
            name="perceptor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profissionalsaude",
            name="residente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="especialista",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_especialista",
                to="comum.profissionalsaude",
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="estabelecimento",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comum.estabelecimentosaude",
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="solicitante",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_solicitante",
                to="comum.profissionalsaude",
            ),
        ),
        migrations.AddField(
            model_name="unidadefederativa",
            name="gestores",
            field=slth.db.models.ManyToManyField(
                blank=True, to="comum.usuario", verbose_name="Gestores"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=slth.db.models.ImageField(
                blank=True, null=True, upload_to="pessoas_fisicas", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="anexousuario",
            name="usuario",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="foto_confirmacao",
                to="comum.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacaosolicitacao",
            name="solicitacao",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avaliacao",
                to="comum.solicitacao",
            ),
        ),
        migrations.AlterField(
            model_name="motivoencerramentoconferencia",
            name="solicitacao",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="motivo_realizacao",
                to="comum.solicitacao",
            ),
        ),
        migrations.AlterField(
            model_name="profissionalsaude",
            name="formacao",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comum.nivelformacao",
            ),
        ),
        migrations.AlterField(
            model_name="profissionalsaude",
            name="usuario",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profissional_saude",
                to="comum.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="profissionalsaudeespecialista",
            name="profissional_saude",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="especialista",
                to="comum.profissionalsaude",
            ),
        ),
        migrations.AlterField(
            model_name="profissionalsaudegestormunicipio",
            name="profissional_saude",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gestor_municipio",
                to="comum.profissionalsaude",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuario",
                to="slth.user",
            ),
        ),
    ]
