# Generated by Django 4.2.6 on 2024-05-09 17:42

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_alter_anexosolicitacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='horario_excepcional',
            field=models.BooleanField(default=False, help_text='Marque essa opção caso deseje agendar em um horário fora da agenda do profissional.', verbose_name='Horário Exceptional'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='justificativa_horario_excepcional',
            field=slth.db.models.TextField(blank=True, help_text='Obrigatório para agendamentos em horário excepcional.', null=True, verbose_name='Justificativa do Horário'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='usuario',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissional_saude', to='comum.usuario', verbose_name='Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='agendado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HorarioProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateField(verbose_name='Data/Hora')),
                ('profissional_saude', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.profissionalsaude', verbose_name='Profissional de Saúde')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='horario_profissional_saude',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comum.horarioprofissionalsaude', verbose_name='Horário'),
        ),
    ]
