# Generated by Django 4.2.6 on 2024-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_solicitacao_horario_excepcional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioprofissionalsaude',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data/Hora'),
        ),
    ]
