# Generated by Django 4.2.6 on 2024-05-11 14:08

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_alter_horarioprofissionalsaude_data_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimentosaude',
            options={'verbose_name': 'Unidade de Saúde', 'verbose_name_plural': 'Unidades de Saúde'},
        ),
        migrations.AddField(
            model_name='especialidade',
            name='area_tematica',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.areatematica', verbose_name='Área Temática'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='avaliacao',
            field=slth.db.models.TextField(blank=True, help_text='Conjunto de campos que possibilita o registro da conclusão feita pelo profissional de saúde a partir dos dados observados nos itens anteriores, como os motivos para aquele encontro, a anamnese do cidadão e dos exames físico e complementares.', null=True, verbose_name='A - avaliacao'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='objetivo',
            field=slth.db.models.TextField(blank=True, help_text='Conjunto de campos que possibilita o registro do exame físico, como os sinais e sintomas detectados, além do registro de resultados de exames realizados.', null=True, verbose_name='O - objetivo'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='plano',
            field=slth.db.models.TextField(blank=True, help_text='Conjunto de funcionalidades que permite registrar o plano de cuidado ao cidadão em relação ao(s) problema(s) avaliado(s).', null=True, verbose_name='P - Plano'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='subjetivo',
            field=slth.db.models.TextField(blank=True, help_text='Conjunto de campos que possibilita o registro da parte subjetiva da anamnese da consulta, ou seja, os dados dos sentimentos e percepções do cidadão em relação à sua saúde.', null=True, verbose_name='S - subjetivo'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='duvida',
            field=slth.db.models.TextField(max_length=2000),
        ),
    ]
