# Generated by Django 4.2.6 on 2024-05-11 15:42

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_alter_estabelecimentosaude_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='vinculo',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='comum.profissionalvinculo'),
        ),
    ]
