# Generated by Django 4.2.7 on 2024-04-20 11:42

from django.db import migrations, models
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='observacao',
        ),
        migrations.AddField(
            model_name='consulta',
            name='anexos',
            field=slth.db.models.OneToManyField(to='app.anexo', verbose_name='Anexos'),
        ),
        migrations.AddField(
            model_name='interacao',
            name='arquivo',
            field=models.FileField(null=True, upload_to='interacoes', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='topico',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topico', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='resposta',
            field=slth.db.models.TextField(blank=True, null=True, verbose_name='Resposta Final'),
        ),
        migrations.AlterField(
            model_name='consultante',
            name='cliente',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='consulta',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consulta', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='cor',
            field=slth.db.models.ColorField(max_length=255, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='assunto',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assunto', verbose_name='Assunto'),
        ),
    ]
