# Generated by Django 4.2.7 on 2024-04-22 06:35

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_situacaoconsulta_consulta_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacaoconsulta',
            name='cor',
            field=slth.db.models.ColorField(default='', max_length=255, verbose_name='Cor'),
            preserve_default=False,
        ),
    ]
