# Generated by Django 4.2.6 on 2024-05-01 12:14

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_arquivo_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntafrequente',
            name='pergunta',
            field=slth.db.models.TextField(verbose_name='Pergunta'),
        ),
    ]
