# Generated by Django 4.2.6 on 2024-05-25 20:37

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', slth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administrador',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('arquivo', slth.db.models.FileField(null=True, upload_to='anexos', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', slth.db.models.CharField(max_length=255, verbose_name='CPF/CNPJ')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('telefone', slth.db.models.CharField(max_length=255, verbose_name='Telefone')),
                ('cpf_responsavel', slth.db.models.CharField(max_length=255, verbose_name='CPF do Responsável')),
                ('nome_responsavel', slth.db.models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('cargo_responsavel', slth.db.models.CharField(max_length=255, verbose_name='Cargo do Responsável')),
                ('email_responsavel', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assuntos', slth.db.models.ManyToManyField(blank=True, to='api.assunto', verbose_name='Assuntos')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', slth.db.models.TextField(verbose_name='Pergunta')),
                ('observacao', slth.db.models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_pergunta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Pergunta')),
                ('data_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Consulta')),
                ('pergunta_ia', slth.db.models.TextField(blank=True, null=True, verbose_name='Pergunta I.A.')),
                ('resposta_ia', slth.db.models.TextField(blank=True, null=True, verbose_name='Resposta I.A.')),
                ('resposta', slth.db.models.TextField(blank=True, null=True, verbose_name='Resposta Final')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('percentual_similaridade_resposta', slth.db.models.IntegerField(null=True, verbose_name='Percentual de Simiralidade da Resposta')),
                ('anexos', slth.db.models.OneToManyField(to='api.anexo', verbose_name='Anexos')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'icon': 'file-signature',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', slth.db.models.CharField(max_length=255, verbose_name='Sigla')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Descrição')),
                ('cor', slth.db.models.ColorField(max_length=255, verbose_name='Cor')),
                ('prazo_resposta', slth.db.models.IntegerField(help_text='Em horas', verbose_name='Prazo para Resposta')),
            ],
            options={
                'verbose_name': 'Prioridade',
                'verbose_name_plural': 'Prioridades',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Descrição')),
                ('codigo_openai', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('assunto', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assunto', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'search_fields': ('assunto__descricao', 'descricao'),
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', slth.db.models.TextField(verbose_name='Pergunta')),
                ('resposta', slth.db.models.TextField(blank=True, verbose_name='Resposta')),
                ('topico', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_frequentes', to='api.topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', slth.db.models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data do Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('cliente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='api.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', slth.db.models.TextField(verbose_name='Mensagem')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('arquivo', slth.db.models.FileField(blank=True, null=True, upload_to='interacoes', verbose_name='Arquivo')),
                ('consulta', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', slth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('registro', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº do Registro Profissional')),
                ('minicurriculo', slth.db.models.TextField(blank=True, null=True, verbose_name='Minicurrículo')),
                ('endereco', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('telefone', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('email', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('assuntos', slth.db.models.ManyToManyField(to='api.assunto', verbose_name='Assuntos')),
                ('estados', slth.db.models.ManyToManyField(to='api.estado', verbose_name='Estados')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Consultante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', slth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('cliente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Consultante',
                'verbose_name_plural': 'Consultantes',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name='consulta',
            name='consultante',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultante', verbose_name='Consultante'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='especialista',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.especialista', verbose_name='Especialista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pergunta_frequente',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.perguntafrequente', verbose_name='Pergunta Frequente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prioridade',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prioridade', verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='topico',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topico', verbose_name='Tópico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estado', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('arquivo', slth.db.models.FileField(null=True, upload_to='arquivos', verbose_name='Arquivo')),
                ('codigo_openai', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('topico', slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='ArquivoCliente',
            fields=[
                ('arquivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.arquivo')),
                ('cliente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Arquivo de Cliente',
                'verbose_name_plural': 'Arquivos de Cliente',
            },
            bases=('api.arquivo', slth.ModelMixin),
        ),
    ]
