services:
  app: &app
    hostname: app
    env_file:
      - base.env
      - local.env
    ports:
      - "8000:8000"
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .deploy/media:/opt/deploy/media
      - .deploy/static:/opt/deploy/static
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl http://127.0.0.1:8000/api/login/
    working_dir: /opt/deploy
    entrypoint: ./entrypoint.sh
  tester:
    <<: *app
    depends_on:
      selenium:
        condition: service_started
    entrypoint: ./test.sh
  selenium:
    hostname: selenium
    env_file:
      - base.env
      - local.env
    ports:
      - "4444"
    build:
      context: selenium
      dockerfile: Dockerfile
    restart: always
    entrypoint: ./run.sh
  redis:
    hostname: redis
    env_file:
      - base.env
      - local.env
    image: redis
    restart: always
    ports:
      - "6379"
    command: redis-server --loglevel warning
    volumes:
      - .deploy/redis:/data
  postgres:
    env_file:
      - base.env
      - local.env
    image: postgres
    hostname: postgres
    ports:
      - "5432"
    volumes:
      - .deploy/postgres:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -d $$POSTGRES_DB -c "SELECT version();"
