# Generated by Django 4.2.6 on 2024-05-21 14:01

from django.db import migrations, models
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='teleconsultor',
            field=models.BooleanField(default=True, verbose_name='Teleconsultor'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='teleinterconsultor',
            field=models.BooleanField(default=True, verbose_name='Teleinterconsultor'),
        ),
        migrations.RemoveField(
            model_name='unidadeorganizacional',
            name='estados',
        ),
        migrations.RemoveField(
            model_name='unidadeorganizacional',
            name='municipios',
        ),
        migrations.RemoveField(
            model_name='unidadeorganizacional',
            name='unidades',
        ),
        migrations.AddField(
            model_name='unidadeorganizacional',
            name='estados',
            field=slth.db.models.ManyToManyField(blank=True, to='app.estado', verbose_name='Estados'),
        ),
        migrations.AddField(
            model_name='unidadeorganizacional',
            name='municipios',
            field=slth.db.models.ManyToManyField(blank=True, to='app.municipio', verbose_name='Municípios'),
        ),
        migrations.AddField(
            model_name='unidadeorganizacional',
            name='unidades',
            field=slth.db.models.ManyToManyField(blank=True, to='app.unidade', verbose_name='Unidades'),
        ),
    ]
