# Generated by Django 4.2.6 on 2024-05-21 17:40

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profissionalsaude_teleconsultor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='assunto',
            field=slth.db.models.CharField(max_length=200, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='duvida',
            field=slth.db.models.TextField(max_length=2000, verbose_name='Dúvida/Queixa'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=slth.db.models.CharField(max_length=7, unique=True),
        ),
    ]
