# Generated by Django 4.2.6 on 2024-05-22 04:39

from django.db import migrations, models
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_unidadeorganizacional_nucleo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nucleo',
            options={'verbose_name': 'Núcleo', 'verbose_name_plural': 'Núcleos'},
        ),
        migrations.RemoveField(
            model_name='profissionalsaude',
            name='uo',
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='estados',
            field=slth.db.models.ManyToManyField(blank=True, to='app.estado', verbose_name='Estados'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='informar_atuacao',
            field=models.BooleanField(default=False, help_text='Marque essa opção caso o profissional vá atuar em unidades diferentes daquelas definidas para o núcleo.', verbose_name='Informar atuação'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='municipios',
            field=slth.db.models.ManyToManyField(blank=True, to='app.municipio', verbose_name='Municípios'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='nucleo',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nucleo', verbose_name='Núcleo'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='unidades',
            field=slth.db.models.ManyToManyField(blank=True, to='app.unidade', verbose_name='Unidades'),
        ),
    ]
