# Generated by Django 4.2.6 on 2024-05-22 10:26

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_nucleo_options_remove_profissionalsaude_uo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nucleo',
            options={'verbose_name': 'Núcleo de Telesaúde', 'verbose_name_plural': 'Núcleos de Telesaúde'},
        ),
        migrations.AddField(
            model_name='anexoatendimento',
            name='nome',
            field=slth.db.models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
    ]
