# Generated by Django 4.2.6 on 2024-05-23 06:03

from django.db import migrations, models
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_nucleo_options_anexoatendimento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='pode_atualizar_agenda',
            field=models.BooleanField(default=True, help_text='Marque essa opção caso o profissional possa informar os dias e horários de seus atendimentos.', verbose_name='Pode Atualizar Agenda'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='horario_especialista',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento2', to='app.horarioprofissionalsaude', verbose_name='Horário'),
        ),
    ]
