# Generated by Django 4.2.6 on 2024-05-23 07:28

from django.db import migrations, models
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profissionalsaude_pode_atualizar_agenda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissionalsaude',
            options={'verbose_name': 'Profissional de Saúde', 'verbose_name_plural': 'Profissionais de Saúde'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=slth.db.models.CharField(max_length=2, unique=True, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=slth.db.models.CharField(max_length=60, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=slth.db.models.CharField(max_length=2, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=slth.db.models.CharField(max_length=7, unique=True, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=slth.db.models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='perceptor',
            field=models.BooleanField(default=False, verbose_name='Perceptor'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='programa_mais_medico',
            field=models.BooleanField(default=False, verbose_name='Programa Mais Médico'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='programa_provab',
            field=models.BooleanField(default=False, verbose_name='Programa PROVAB'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='residente',
            field=models.BooleanField(default=False, verbose_name='Residente'),
        ),
    ]
