# Generated by Django 4.1 on 2024-04-11 22:08

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', slth.db.models.CharField(max_length=255, verbose_name='E-mail')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('gerente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', slth.db.models.IntegerField(verbose_name='DDD')),
                ('numero', slth.db.models.CharField(max_length=25, verbose_name='Número')),
            ],
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('supervisor', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('loja', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loja')),
            ],
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(help_text='Nome completo', max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('salario', slth.db.models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salário')),
                ('casado', models.BooleanField(blank=True, default=False, verbose_name='Casado?')),
                ('sexo', slth.db.models.CharField(blank=True, choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=255, null=True, verbose_name='Sexo')),
                ('cor_preferida', slth.db.models.ColorField(blank=True, max_length=255, null=True, verbose_name='Cor Preferida')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto')),
                ('telefone_pessoal', slth.db.models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='app.telefone', verbose_name='Telefone Pessoal')),
                ('telefones_profissionais', slth.db.models.OneToManyField(to='app.telefone', verbose_name='Telefones Profissionais')),
            ],
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name='loja',
            name='rede',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rede'),
        ),
        migrations.AddField(
            model_name='loja',
            name='vendedores',
            field=slth.db.models.ManyToManyField(related_name='r1', to='app.funcionario'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('prefeito', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Prefeito')),
                ('vereadores', slth.db.models.ManyToManyField(blank=True, related_name='r1', to='app.pessoa', verbose_name='Vereadores')),
            ],
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
