# Generated by Django 4.2.7 on 2024-04-16 04:53

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estado_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', slth.db.models.TextField(verbose_name='Enunciado')),
                ('tipo_resposta', slth.db.models.IntegerField(verbose_name='Tipo da Resposta')),
                ('resposta_obrigatoria', models.BooleanField(blank=True, verbose_name='Resposta Obrigatória')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('cpf', slth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='InstrumentoAvaliativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_termino', models.DateField(verbose_name='Término')),
                ('instrucoes', slth.db.models.TextField(blank=True, null=True, verbose_name='Instruções')),
                ('responsavel', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoafisica', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Instrumento Avaliativo',
                'verbose_name_plural': 'Instrumentos Avaliativos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
