# Generated by Django 4.2.7 on 2024-04-16 05:01

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pergunta_pessoafisica_instrumentoavaliativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='instrumento_avaliativo',
            field=slth.db.models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.instrumentoavaliativo', verbose_name='Instrumento Avaliativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='email',
            field=slth.db.models.CharField(default=None, max_length=255, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='telefone',
            field=slth.db.models.CharField(default=None, max_length=255, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
