# Generated by Django 4.2.7 on 2024-04-16 05:51

from django.db import migrations, models
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pergunta_instrumento_avaliativo_pessoafisica_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo_resposta',
            field=slth.db.models.IntegerField(choices=[(1, 'Texto curso'), (2, 'Texto longo'), (3, 'Data'), (4, 'Decimal'), (5, 'Inteiro'), (6, 'Escolha'), (7, 'Múltipla Escolha')], verbose_name='Tipo da Resposta'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas_fisicas', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='opcoes',
            field=slth.db.models.OneToManyField(to='app.opcaoresposta', verbose_name='Opções de Resposta'),
        ),
    ]
