# Generated by Django 4.2.6 on 2024-05-04 14:46

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_questionario_perguntaquestionario_questionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=slth.db.models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='foto',
            field=slth.db.models.ImageField(blank=True, null=True, upload_to='pessoas_fisicas', verbose_name='Foto'),
        ),
    ]
