# Generated by Django 4.2.6 on 2024-05-25 22:03

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', slth.db.models.CharField(max_length=255, verbose_name='Sigla')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', slth.db.models.CharField(max_length=255, verbose_name='E-mail')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='InstrumentoAvaliativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_termino', models.DateField(verbose_name='Término')),
                ('instrucoes', slth.db.models.TextField(blank=True, null=True, verbose_name='Instruções')),
            ],
            options={
                'verbose_name': 'Instrumento Avaliativo',
                'verbose_name_plural': 'Instrumentos Avaliativos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('gerente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.funcionario')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', slth.db.models.TextField(verbose_name='Enunciado')),
                ('tipo_resposta', slth.db.models.IntegerField(choices=[(1, 'Texto curso'), (2, 'Texto longo'), (3, 'Data'), (4, 'Decimal'), (5, 'Inteiro'), (6, 'Escolha'), (7, 'Múltipla Escolha')], verbose_name='Tipo da Resposta')),
                ('resposta_obrigatoria', models.BooleanField(blank=True, verbose_name='Resposta Obrigatória')),
                ('instrumento_avaliativo', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instrumentoavaliativo', verbose_name='Instrumento Avaliativo')),
                ('opcoes', slth.db.models.OneToManyField(to='api.opcaoresposta', verbose_name='Opções de Resposta')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', slth.db.models.ImageField(blank=True, null=True, upload_to='pessoas_fisicas', verbose_name='Foto')),
                ('cpf', slth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', slth.db.models.CharField(max_length=255, verbose_name='Telefone')),
                ('email', slth.db.models.CharField(max_length=255, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', slth.db.models.IntegerField(verbose_name='DDD')),
                ('numero', slth.db.models.CharField(max_length=25, verbose_name='Número')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('supervisor', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.funcionario')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_avaliativo', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instrumentoavaliativo', verbose_name='Instrumento Avaliativo')),
                ('respondente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pessoafisica', verbose_name='Respondente')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('loja', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loja')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(help_text='Nome completo', max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('salario', slth.db.models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salário')),
                ('casado', models.BooleanField(blank=True, default=False, verbose_name='Casado?')),
                ('sexo', slth.db.models.CharField(blank=True, choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=255, null=True, verbose_name='Sexo')),
                ('cor_preferida', slth.db.models.ColorField(blank=True, max_length=255, null=True, verbose_name='Cor Preferida')),
                ('foto', slth.db.models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto')),
                ('telefone_pessoal', slth.db.models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='api.telefone', verbose_name='Telefone Pessoal')),
                ('telefones_profissionais', slth.db.models.OneToManyField(to='api.telefone', verbose_name='Telefones Profissionais')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='PerguntaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Resposta')),
                ('pergunta', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pergunta', verbose_name='Pergunta')),
                ('questionario', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questionario', verbose_name='Questionário')),
            ],
            options={
                'verbose_name': 'Pergunta de Questionário',
                'verbose_name_plural': 'Perguntas de Questionário',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('estado', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name='loja',
            name='rede',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rede'),
        ),
        migrations.AddField(
            model_name='loja',
            name='vendedores',
            field=slth.db.models.ManyToManyField(related_name='r1', to='api.funcionario'),
        ),
        migrations.AddField(
            model_name='instrumentoavaliativo',
            name='responsavel',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pessoafisica', verbose_name='Responsável'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('prefeito', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pessoa', verbose_name='Prefeito')),
                ('vereadores', slth.db.models.ManyToManyField(blank=True, related_name='r1', to='api.pessoa', verbose_name='Vereadores')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
