# Generated by Django 4.2.7 on 2024-04-16 07:51

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_opcaoresposta_alter_pergunta_tipo_resposta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_avaliativo', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instrumentoavaliativo', verbose_name='Instrumento Avaliativo')),
                ('respondente', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoafisica', verbose_name='Respondente')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PerguntaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Resposta')),
                ('Questionario', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionario', verbose_name='Questionário')),
                ('pergunta', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta de Questionário',
                'verbose_name_plural': 'Perguntas de Questionário',
            },
            bases=(models.Model,),
        ),
    ]
