# Generated by Django 4.2.7 on 2024-04-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_questionario_perguntaquestionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntaquestionario',
            old_name='Questionario',
            new_name='questionario',
        ),
    ]
