# Generated by Django 4.2.7 on 2024-04-17 06:01

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_questionario_perguntaquestionario_questionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição')),
                ('curso', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Escolaridade',
                'verbose_name_plural': 'Escolaridades',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Esfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Esfera',
                'verbose_name_plural': 'Esferas',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nível de Ensino',
                'verbose_name_plural': 'Níveis de Ensino',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', slth.db.models.CharField(max_length=255, verbose_name='Sigla')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', slth.db.models.CharField(max_length=255, verbose_name='CNPJ')),
                ('esfera', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.esfera', verbose_name='Esfera')),
            ],
            options={
                'verbose_name': 'Orgão',
                'verbose_name_plural': 'Orgãos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Poder',
                'verbose_name_plural': 'Poderes',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacao', slth.db.models.CharField(max_length=255, verbose_name='Informação')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='SituacaoEscolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Situação de Escolaridade',
                'verbose_name_plural': 'Situações de Escolaridade',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Orgão',
                'verbose_name_plural': 'Tipos de Orgãos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoRedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Rede Social',
                'verbose_name_plural': 'Tipos de Rede Social',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.RemoveField(
            model_name='loja',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='rede',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='vendedores',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone_pessoal',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefones_profissionais',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='rede',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='nome_social',
            field=slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Social'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Rede',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
        migrations.AddField(
            model_name='redesocial',
            name='pessoa_fisica',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AddField(
            model_name='redesocial',
            name='tipo',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiporedesocial', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='orgao',
            name='poder',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poder', verbose_name='Poder'),
        ),
        migrations.AddField(
            model_name='orgao',
            name='tipo',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoorgao', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='nivel_ensino',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nivelensino', verbose_name='Nível de Ensino'),
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='pessoa_fisica',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoafisica', verbose_name='Pessoa Física'),
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='situacao',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.situacaoescolaridade', verbose_name='Situação'),
        ),
    ]
