# Generated by Django 4.2.6 on 2024-05-26 19:40

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='horarios_especialista',
            field=slth.db.models.ManyToManyField(blank=True, related_name='atendimentos_especialista', to='api.horarioprofissionalsaude', verbose_name='Horários'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horarios_profissional_saude',
            field=slth.db.models.ManyToManyField(blank=True, related_name='atendimentos_profissional_saude', to='api.horarioprofissionalsaude', verbose_name='Horários'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='profissional',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_profissional', to='api.profissionalsaude', verbose_name='Profissional Responsável'),
        ),
    ]
