# Generated by Django 4.2.6 on 2024-05-26 19:40

from django.db import migrations


def migrate(apps, schema):
    Atendimento = apps.get_model('api.Atendimento')
    for a in Atendimento.objects.all():
        a.horarios_profissional_saude.add(a.horario_profissional_saude)
        if a.horario_especialista:
            a.horarios_especialista.add(a.horario_especialista)
        print(a.id, a.horarios_profissional_saude.count(), a.horarios_especialista.count())


def unmigrate(apps, schema):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_atendimento_horarios_especialista_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate, unmigrate)
    ]
