# Generated by Django 4.2.6 on 2024-06-09 19:31

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240526_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='horario_especialista',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='horario_profissional_saude',
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='unidade',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unidade', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='unidades',
            field=slth.db.models.ManyToManyField(blank=True, related_name='r2', to='api.unidade', verbose_name='Unidades'),
        ),
    ]
