# Generated by Django 4.2.6 on 2024-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_nucleo_estados_remove_nucleo_municipios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='termo_assinado_especialista',
            field=models.BooleanField(default=False, verbose_name='Termo assinado pelo Especialista'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='termo_assinado_paciente',
            field=models.BooleanField(default=False, verbose_name='Termo assinado pelo Paciente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='termo_assinado_profissional',
            field=models.BooleanField(default=False, verbose_name='Termo assinado pelo Profissional'),
        ),
    ]
