# Generated by Django 4.2.6 on 2024-06-16 19:40

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profissionalsaude_registro_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='avaliacao',
            field=slth.db.models.TextField(blank=True, help_text='Conjunto de campos que possibilita o registro da conclusão feita pelo profissional de saúde a partir dos dados observados nos itens anteriores, como os motivos para aquele encontro, a anamnese do cidadão e dos exames físico e complementares.', null=True, verbose_name='A - avaliação'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='comentario',
            field=slth.db.models.TextField(blank=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='conduta',
            field=slth.db.models.TextField(blank=True, null=True, verbose_name='Conduta'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='encaminhamento',
            field=slth.db.models.TextField(blank=True, null=True, verbose_name='Encaminhamento'),
        ),
    ]
