# Generated by Django 4.2.6 on 2024-06-17 09:56

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_encaminhamentoscondutas_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='email',
            field=slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='telefone',
            field=slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
