# Generated by Django 4.2.6 on 2024-06-23 18:34

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pessoafisica_email_alter_pessoafisica_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='zoom_token',
            field=slth.db.models.TextField(blank=True, null=True, verbose_name='Zoom Token'),
        ),
    ]
