# Generated by Django 4.2.6 on 2024-07-08 09:33

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_documento_profissionalsaude_vidaas_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', slth.db.models.CharField(choices=[[0, 'SEG'], [1, 'TER'], [2, 'QUA'], [3, 'QUI'], [4, 'SEX'], [5, 'SAB'], [6, 'DOM']], max_length=255, verbose_name='Dia da Semana')),
                ('hora', slth.db.models.IntegerField(verbose_name='Hora')),
                ('minuto', slth.db.models.IntegerField(verbose_name='Minuto')),
                ('profissional_saude', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profissionalsaude', verbose_name='Profissional de Saúde')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
