# Generated by Django 4.2.6 on 2024-07-09 16:28

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_horarioatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalsaude',
            name='sigla_conselho_registro_especialista',
            field=slth.db.models.CharField(max_length=30, null=True, verbose_name='Sigla do Conselho do Registro de Especialista'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='sigla_conselho_registro_profissional',
            field=slth.db.models.CharField(max_length=30, null=True, verbose_name='Sigla do Conselho do Registro Profissional'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='uf_registro_especialista',
            field=slth.db.models.CharField(max_length=30, null=True, verbose_name='UF do Registro de Especialista'),
        ),
        migrations.AddField(
            model_name='profissionalsaude',
            name='uf_registro_profissional',
            field=slth.db.models.CharField(max_length=30, null=True, verbose_name='UF do Registro Profissional'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='registro_especialista',
            field=slth.db.models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº do Registro de Especialista'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='registro_profissional',
            field=slth.db.models.CharField(max_length=30, verbose_name='Nº do Registro Profissional'),
        ),
    ]
