# Generated by Django 4.2.6 on 2024-07-09 18:22

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profissionalsaude_sigla_conselho_registro_especialista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='cbo',
            field=slth.db.models.CharField(blank=True, max_length=6, null=True, verbose_name='Código'),
        ),
    ]
