# Generated by Django 4.2.6 on 2024-07-09 18:33

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_especialidade_cbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalsaude',
            name='uf_registro_especialista',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r2', to='api.estado', verbose_name='UF do Registro de Especialista'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='uf_registro_profissional',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estado', verbose_name='UF do Registro Profissional'),
        ),
    ]
