# Generated by Django 4.2.6 on 2024-07-13 14:04

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_atendimento_termo_assinado_especialista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='especialista',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_especialista', to='api.profissionalsaude'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='conselho_especialista',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r3', to='api.conselhoclasse', verbose_name='Conselho de Especialista'),
        ),
    ]
