# Generated by Django 4.2.6 on 2024-07-13 15:30

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_atendimento_especialista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoatendimento',
            name='assinaturas',
            field=slth.db.models.ManyToManyField(blank=True, related_name='anexos_assinados', to='api.pessoafisica', verbose_name='Assinaturas'),
        ),
    ]
