# Generated by Django 4.2.6 on 2024-07-14 08:12

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_anexoatendimento_assinaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='token',
            field=slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
    ]
