# Generated by Django 4.2.7 on 2024-04-21 15:01

from django.db import migrations, models
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_anexo_consulta_remove_anexo_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', slth.db.models.CharField(max_length=255, verbose_name='CPF')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administrador',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='interacoes', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='mensagem',
            field=slth.db.models.TextField(verbose_name='Mensagem'),
        ),
    ]
