# Generated by Django 4.2.7 on 2024-04-22 06:27

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_administrador_alter_interacao_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Situação de Consulta',
                'verbose_name_plural': 'Situações de Consulta',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name='consulta',
            name='situacao',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.situacaoconsulta', verbose_name='Situação'),
        ),
    ]
