# Generated by Django 4.2.7 on 2024-04-23 09:54

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_consulta_situacao_delete_situacaoconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='pergunta_frequente',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.perguntafrequente', verbose_name='Pergunta Frequente'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=slth.db.models.FileField(null=True, upload_to='anexos', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=slth.db.models.FileField(null=True, upload_to='arquivos', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='arquivo',
            field=slth.db.models.FileField(blank=True, null=True, upload_to='interacoes', verbose_name='Arquivo'),
        ),
    ]
