# Generated by Django 4.2.6 on 2024-07-15 20:39

from django.db import migrations, models
import slth
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_atendimento_area_atendimento_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(help_text='Ex: Hemograma completo', max_length=255, verbose_name='Nome')),
                ('detalhe', slth.db.models.CharField(blank=True, help_text='Ex: COVID', max_length=255, null=True, verbose_name='Detalhe')),
            ],
            options={
                'verbose_name': 'Tipo de Exame',
                'verbose_name_plural': 'Tipos de Exames',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
