# Generated by Django 4.2.6 on 2024-07-15 20:50

from django.db import migrations
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexame',
            name='tuss',
            field=slth.db.models.CharField(max_length=255, null=True, verbose_name='TUSS'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='detalhe',
            field=slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalhe'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='nome',
            field=slth.db.models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
