# Generated by Django 4.2.6 on 2024-08-12 09:09

from django.db import migrations
import django.db.models.deletion
import slth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='profissional_saude',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profissionalsaude', verbose_name='Profissional de Saúde'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='profissional_saude',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profissionalsaude', verbose_name='Profissional de Saúde'),
        ),
    ]
