# Generated by Django 4.2.6 on 2024-08-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicamento_profissional_saude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
    ]
