application:
  lang: pt-br
  title: Tele Fiocruz
  subtitle: Sistema de Telessaúde da Fiocruz
  icon: /static/images/icon.png
  logo: /static/images/logo.png
  version: 1.0.5
  sponsors:
    - /static/images/logos/logo4.png
  oauth:
    govbr:
      name: SUAP
      client_id: BWcQGJ2VMDtkIVyMi50vwarhQE6U3JkMoVOEjgFf
      client_secret: o6fOH3bOHd3BxGzAN7KcT3vJTnDI3N9IGmfNqHXq23ocOMhvnTGSSHf2DpGdzyABvCSKZ6CpnhUUtEG3W7R4w9MMvYNH3dPBOPxbo7iNhcaTaFg1hjugrbJ7QjYiNKfn
      redirect_uri: /app/login/
      authorize_url: https://suaptreino.cfmv.gov.br/o/authorize/
      access_token_url: https://suaptreino.cfmv.gov.br/o/token/
      user_data_url: https://suaptreino.cfmv.gov.br/api/eu/
      user_logout_url: 
      user_scope:
      user_data:
        create: true
        username: identificacao
        email: email
  groups:
    g: Gestor de Unidade Organizacional
    o: Operador de Unidade Organizacional
    ps: Profissinal de Saúde
    p: Paciente
  index: dashboard
  dashboard:
    toolbar:
      - pessoasfisicas
      - profissionaissaude
      - atendimentos
    actions:
    top:
    center:
      - meusvinculos
      - proximosatendimentosprofissionalsaude
      - proximosatendimentospaciente
      - minhaagenda
    boxes:
      - pessoasfisicas
      - nucleos
      - unidades
      - profissionaissaude
      - definirhorarioprofissionaissaude
      - atendimentos
      - agendaatendimentos
      - estatistica
    adder:
    search:
    usermenu:
      #- icons
      - users
      - logout
    tools:
    settings:
  menu:
    list:Cadastros Gerais:
      CIDs: cids
      CIAPs: ciaps
      Níveis de Formacão: niveisformacao
      Sexos: sexos
      Tipos de Atendimento: tiposatendimento
      Estados: unidadesfederativas
      Municípios: municipios
      Áreas: areas
      Especialidades: especialidades
    building-user:Núcleos de Telesaúde: nucleos
    building:Unidades de Saúde: unidades
    stethoscope:Profissionais de Saúde: profissionaissaude
    users:Pessoas Físicas: pessoafisicas
    laptop-file:Teleconsultas: atendimentos
    #file-signature:Certificados Digitais: certificadosdigitais
  theme:
    colors:
      primary: "#265890"
      secondary: "#071e41"
      auxiliary: "#2670e8"
      highlight: "#0c326f"
      info: "#265890"
      success: "#5ca05d"
      warning: "#fff5c2"
      danger: "#e52207"
    border:
      radius: 100em"
    background:
      info: "#d4e5ff"
