# Generated by Django 4.2.6 on 2024-05-03 12:16

from django.db import migrations, models
import django.db.models.deletion
import slth
import slth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('sigla', slth.db.models.CharField(max_length=25, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Conselho',
                'verbose_name_plural': 'Conselhos',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', slth.db.models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='TipoLegislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', slth.db.models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Legislação',
                'verbose_name_plural': 'Tipos de Legislação',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Relator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('numero_crmv', slth.db.models.CharField(max_length=25, verbose_name='Nº CRMV')),
                ('classe', slth.db.models.CharField(choices=[['V', 'Médico-Veterinário'], ['Z', 'Zootecnista']], max_length=100, verbose_name='Classe')),
                ('conselho', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conselho', verbose_name='Conselho')),
            ],
            options={
                'verbose_name': 'Relator',
                'verbose_name_plural': 'Relatores',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name='conselho',
            name='estado',
            field=slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', slth.db.models.CharField(max_length=255, verbose_name='Número')),
                ('ano', slth.db.models.IntegerField(verbose_name='Ano')),
                ('data', models.DateField(verbose_name='Data')),
                ('ementa', slth.db.models.TextField(verbose_name='Ementa')),
                ('conteudo', slth.db.models.TextField(verbose_name='Conteúdo')),
                ('arquivo', slth.db.models.FileField(upload_to='acordao', verbose_name='Arquivo')),
                ('data_dou', models.DateField(verbose_name='Data de Publicação')),
                ('secao_dou', slth.db.models.CharField(max_length=100, verbose_name='Seção da Publicação')),
                ('pagina_dou', slth.db.models.CharField(max_length=100, verbose_name='Página da Publicação')),
                ('codigo', slth.db.models.IntegerField(null=True, verbose_name='Código')),
                ('revogada_por', slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.legislacao', verbose_name='Revogada Por')),
                ('tipo', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipolegislacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Legislação',
                'verbose_name_plural': 'Legislações',
                'unique_together': {('numero', 'ano', 'tipo')},
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name='Acordao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', slth.db.models.CharField(max_length=255, verbose_name='Número')),
                ('ano', slth.db.models.IntegerField(verbose_name='Ano')),
                ('data_dou', models.DateField(verbose_name='Data de Publicação no DOU')),
                ('orgao_julgador', slth.db.models.CharField(choices=[['Plenário', 'Plenário'], ['Primeira Turma', 'Primeira Turma'], ['Segunda Turma', 'Segunda Turma']], max_length=100, verbose_name='Órgão Julgador')),
                ('natureza', slth.db.models.CharField(choices=[['Processo Administrativo', 'Processo Administrativo'], ['Processo Ético-Profissional', 'Processo Ético-Profissional']], max_length=100, verbose_name='Natureza')),
                ('ementa', slth.db.models.TextField(verbose_name='Ementa')),
                ('conteudo', slth.db.models.TextField(verbose_name='Conteúdo')),
                ('arquivo', slth.db.models.FileField(upload_to='acordao', verbose_name='Arquivo')),
                ('processo', slth.db.models.CharField(max_length=255, verbose_name='Processo')),
                ('relator', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.relator', verbose_name='Relator')),
            ],
            options={
                'verbose_name': 'Acórdão',
                'verbose_name_plural': 'Acórdãos',
                'unique_together': {('numero', 'ano', 'natureza', 'orgao_julgador')},
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
