# Generated by Django 5.1.1 on 2024-09-16 11:01

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slth', '0008_alter_deletion_datetime_alter_log_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='from_email',
        ),
        migrations.AddField(
            model_name='email',
            name='action',
            field=slth.db.models.CharField(max_length=255, null=True, verbose_name='Ação'),
        ),
        migrations.AddField(
            model_name='email',
            name='attempt',
            field=slth.db.models.IntegerField(default=0, verbose_name='Tentativa de Envio'),
        ),
        migrations.AddField(
            model_name='email',
            name='error',
            field=slth.db.models.TextField(null=True, verbose_name='Erro'),
        ),
        migrations.AddField(
            model_name='email',
            name='send_at',
            field=slth.db.models.DateTimeField(null=True, verbose_name='Data/Hora'),
        ),
        migrations.AddField(
            model_name='email',
            name='url',
            field=slth.db.models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
