# Generated by Django 5.1.3 on 2024-12-05 14:14

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slth', '0011_usertimezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fuso Horário',
                'verbose_name_plural': 'Fusos Horários',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.RemoveField(
            model_name='usertimezone',
            name='key',
        ),
        migrations.AddField(
            model_name='usertimezone',
            name='timezone',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slth.timezone', verbose_name='Fuso Horário'),
        ),
    ]
