# Generated by Django 5.1.3 on 2025-01-23 14:16

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slth', '0012_timezone_remove_usertimezone_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', slth.db.models.CharField(max_length=255, verbose_name='To')),
                ('title', slth.db.models.CharField(max_length=255, verbose_name='Subject')),
                ('message', slth.db.models.TextField(verbose_name='Content')),
                ('url', slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('send_at', slth.db.models.DateTimeField(blank=True, null=True, verbose_name='Send at')),
                ('sent_at', slth.db.models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('attempt', slth.db.models.IntegerField(blank=True, default=0, verbose_name='Attempt')),
                ('error', slth.db.models.TextField(blank=True, null=True, verbose_name='Error')),
                ('key', slth.db.models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Whatsapp Notification',
                'verbose_name_plural': 'Whatsapp Notifications',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
