# Generated by Django 5.1.1 on 2025-03-23 14:21

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slth", "0013_whatsappnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", slth.db.models.CharField(max_length=255, verbose_name="Chave")),
                (
                    "value",
                    slth.db.models.CharField(max_length=255, verbose_name="Value"),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
                "icon": "gears",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
