# Generated by Django 5.1.1 on 2025-04-12 11:26

from django.db import migrations
from slth import timezone

def migrate(apps, editor):
    TimeZone = apps.get_model('slth', 'TimeZone')
    TimeZone.objects.filter(name='Etc/GMT+4').update(name='Etc/GMT-4')
    TimeZone.objects.filter(name='Etc/GMT+3').update(name='Etc/GMT-3')
    for instance in TimeZone.objects.all():
        name = timezone.get_timezone(instance.name).zone
        print(instance.name, name)
        instance.name = name
        instance.save()

def unmigrate(apps, editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("slth", "0014_settings"),
    ]

    operations = [
        migrations.RunPython(migrate, unmigrate)
    ]
